### ISSUE TITLE
JSON Support

### ISSUE THREAD

**Issue by piperchester** [vilic/vscode-es-quotes#19]
Love the extension. Thank you for writing it!

What do you think about building support for JSON? I currently get the "language not supported" error. Do you think this functionality would be a good add for the extension, or better suited elsewhere?

**Comment by joshkopecek** [comment]
@piperchester there is already a pull request here: https://github.com/vilic/vscode-es-quotes/pull/15
@JELaVallee
@vilic could we get this merged?

**Comment by vilicvane** [comment]
Hi, sorry for the late response. The reason I am not tend to enable this in JSON file is that there should be better tools available.

I just did some searching and found an extension called "Fix JSON": https://github.com/oliversturm/vscode-fix-json

**Comment by joshkopecek** [comment]
@vilic this extension is simple for toggling between different quote types, and I don't see why you wouldn't enable that for json. Fix JSON has completely different functionality. What do you think?

**Comment by vilicvane** [comment]
@joshkopecek You know what, I just merged the PR. 😂

**Comment by joshkopecek** [comment]
@vilic nice one! Would be cool to have filetypes potentially editable in settings ;-)

**Comment by vilicvane** [comment]
@joshkopecek Does VS Code support something like that now? Will take a look.

**Comment by joshkopecek** [comment]
@vilic yes, you can grab settings easily
```
workspace.getConfiguration('esQuotes').get('supportedFiletypes')
```

**Comment by vilicvane** [comment]
@joshkopecek Ahh, sure. I was thinking about wrong things.

**Comment by joshkopecek** [comment]
@vilic can make a PR, but probable not immediately?

**Comment by vilicvane** [comment]
@joshkopecek Sure. When you do, please make it `supportedLanguages` though. Thanks!
