### ISSUE TITLE
JSX support

### ISSUE THREAD

**Issue by mihe** [vilic/vscode-es-quotes#3]
Any chance of getting support for files using JSX (*.jsx, *.tsx)? I think VS Code refers to them as "JavaScript React" and "TypeScript React". Just having support for the JavaScript/TypeScript part of it (i.e. not the embedded HTML) would be fine with me.

**Comment by DavidBabel** [comment]
Any way to deploy it for the official extension ? seems not up to date on marketplace : https://marketplace.visualstudio.com/items?itemName=vilicvane.es-quotes#review-details

**Comment by vilicvane** [comment]
@DavidBabel published.

**Comment by DavidBabel** [comment]
Nice 👍
